import { Activity, ArrowRight, BrainCircuit, Check, GitCompareArrows, History, Link2, Network, Plus, Save, Search, ShieldAlert, Trash2, TrendingDown, TrendingUp } from 'lucide-react'
import { type FormEvent, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { api, formatDate } from '../lib/api'
import type { AssumptionStatus, Decision, DecisionGraph, DecisionVersion, ReplayComparison, SemanticSearchResult } from '../types'
import { ErrorNotice } from './UI'

const statuses: AssumptionStatus[] = ['UNKNOWN', 'ACTIVE', 'STRENGTHENED', 'WEAKENING', 'BROKEN']
const relations = ['DEPENDS_ON', 'CAUSED_BY', 'FOLLOW_UP', 'REPLACES', 'SUPPORTS', 'CONFLICTS_WITH', 'RELATED_TO']

export function DecisionIntelligencePanel({ id, decision, original, isReplay, replayAt, onReload }: { id: string; decision: Decision; original: Decision; isReplay: boolean; replayAt: number | null; onReload: () => Promise<void> }) {
  const [versions, setVersions] = useState<DecisionVersion[]>([])
  const [similar, setSimilar] = useState<SemanticSearchResult | null>(null)
  const [allDecisions, setAllDecisions] = useState<Decision[]>([])
  const [graph, setGraph] = useState<DecisionGraph | null>(null)
  const [comparison, setComparison] = useState<ReplayComparison | null>(null)
  const [error, setError] = useState('')
  const [showEdit, setShowEdit] = useState(false)
  const [edit, setEdit] = useState({ title: original.title, decision: original.decision, reason: original.reason, changeReason: '' })
  const [confidence, setConfidence] = useState(original.confidence)
  const [confidenceReason, setConfidenceReason] = useState('')
  const [assumption, setAssumption] = useState('')
  const [assumptionReasons, setAssumptionReasons] = useState<Record<string, string>>({})
  const [invalidation, setInvalidation] = useState('')
  const [invalidationNotes, setInvalidationNotes] = useState<Record<string, string>>({})
  const [linkForm, setLinkForm] = useState({ targetDecisionId: '', relationType: 'RELATED_TO', description: '' })
  const load = async () => {
    try {
      const [versionValue, similarValue, listValue, graphValue] = await Promise.all([
        api<{ items: DecisionVersion[] }>(`/api/v1/decisions/${id}/versions`),
        api<SemanticSearchResult>(`/api/v1/decisions/${id}/similar`),
        api<{ items: Decision[] }>('/api/v1/decisions?limit=100'),
        api<DecisionGraph>(`/api/v1/decisions/${id}/graph?depth=1`),
      ])
      setVersions(versionValue.items); setSimilar(similarValue); setAllDecisions(listValue.items.filter(item => item.id !== id)); setGraph(graphValue)
    } catch (err) { setError(err instanceof Error ? err.message : 'Decision Intelligence를 불러오지 못했습니다.') }
  }
  useEffect(() => { void load() }, [id, original.version])
  useEffect(() => { setEdit({ title: original.title, decision: original.decision, reason: original.reason, changeReason: '' }); setConfidence(original.confidence) }, [original])
  const compare = async () => { if (!replayAt) return; try { setComparison(await api<ReplayComparison>(`/api/v1/decisions/${id}/replay/compare?from=${encodeURIComponent(new Date(replayAt).toISOString())}&to=${encodeURIComponent(new Date().toISOString())}`)) } catch (err) { setError(err instanceof Error ? err.message : '시점을 비교하지 못했습니다.') } }
  const updateDecision = async (event: FormEvent) => { event.preventDefault(); try { await api(`/api/v1/decisions/${id}`, { method: 'PATCH', body: JSON.stringify({ ...edit, version: original.version }) }); setShowEdit(false); await onReload() } catch (err) { setError(err instanceof Error ? err.message : '새 버전을 저장하지 못했습니다.') } }
  const updateConfidence = async (event: FormEvent) => { event.preventDefault(); try { await api(`/api/v1/decisions/${id}/confidence`, { method: 'POST', body: JSON.stringify({ confidence, reason: confidenceReason }) }); setConfidenceReason(''); await onReload() } catch (err) { setError(err instanceof Error ? err.message : '확신 변화를 저장하지 못했습니다.') } }
  const addAssumption = async (event: FormEvent) => { event.preventDefault(); try { await api(`/api/v1/decisions/${id}/assumptions`, { method: 'POST', body: JSON.stringify({ assumption, status: 'UNKNOWN' }) }); setAssumption(''); await onReload() } catch (err) { setError(err instanceof Error ? err.message : '전제를 추가하지 못했습니다.') } }
  const updateAssumption = async (assumptionId: string, status: AssumptionStatus) => { const reason = assumptionReasons[assumptionId]?.trim(); if (!reason) { setError('전제 상태가 바뀐 이유를 입력해 주세요.'); return } try { await api(`/api/v1/assumptions/${assumptionId}`, { method: 'PATCH', body: JSON.stringify({ status, reason }) }); setAssumptionReasons(value => ({ ...value, [assumptionId]: '' })); await onReload() } catch (err) { setError(err instanceof Error ? err.message : '전제 상태를 바꾸지 못했습니다.') } }
  const addInvalidation = async (event: FormEvent) => { event.preventDefault(); try { await api(`/api/v1/decisions/${id}/invalidation-conditions`, { method: 'POST', body: JSON.stringify({ condition: invalidation }) }); setInvalidation(''); await onReload() } catch (err) { setError(err instanceof Error ? err.message : '반증 조건을 추가하지 못했습니다.') } }
  const updateInvalidation = async (conditionId: string, status: 'ACTIVE' | 'TRIGGERED' | 'RESOLVED') => { const note = invalidationNotes[conditionId]?.trim() || (status === 'ACTIVE' ? '다시 관찰 중' : ''); if (!note) { setError('반증 조건 상태가 바뀐 근거를 입력해 주세요.'); return } try { await api(`/api/v1/invalidation-conditions/${conditionId}`, { method: 'PATCH', body: JSON.stringify({ status, note }) }); setInvalidationNotes(value => ({ ...value, [conditionId]: '' })); await onReload() } catch (err) { setError(err instanceof Error ? err.message : '반증 조건 상태를 바꾸지 못했습니다.') } }
  const addLink = async (event: FormEvent) => { event.preventDefault(); try { await api(`/api/v1/decisions/${id}/links`, { method: 'POST', body: JSON.stringify(linkForm) }); setLinkForm({ targetDecisionId: '', relationType: 'RELATED_TO', description: '' }); await load() } catch (err) { setError(err instanceof Error ? err.message : '판단을 연결하지 못했습니다.') } }
  const deleteLink = async (linkId: string) => { try { await api(`/api/v1/decision-links/${linkId}`, { method: 'DELETE' }); await load() } catch (err) { setError(err instanceof Error ? err.message : '판단 연결을 해제하지 못했습니다.') } }
  const linkedTitles = useMemo(() => new Map((graph?.nodes || []).map(node => [node.id, node.title])), [graph])
  return <section className="decision-intelligence">{error && <ErrorNotice message={error} />}
    <section className="intelligence-block version-control"><header><div><History size={17} /><h2>Decision Version</h2></div><button className="text-link" onClick={() => setShowEdit(value => !value)}>{showEdit ? '닫기' : `v${original.version} 수정`}</button></header>{showEdit && <form className="version-edit" onSubmit={updateDecision}><label>제목<input value={edit.title} onChange={event => setEdit({ ...edit, title: event.target.value })} required /></label><label>Decision<textarea value={edit.decision} onChange={event => setEdit({ ...edit, decision: event.target.value })} rows={3} required /></label><label>Reason<textarea value={edit.reason} onChange={event => setEdit({ ...edit, reason: event.target.value })} rows={2} /></label><label>무엇이 바뀌었나요?<input value={edit.changeReason} onChange={event => setEdit({ ...edit, changeReason: event.target.value })} placeholder="변경 이유" required /></label><button className="button secondary"><Save size={15} />새 버전 저장</button></form>}<div className="version-timeline">{versions.slice(0, 5).map(version => <article key={version.id}><span>v{version.version}</span><div><strong>{version.title}</strong><p>{version.changeReason}</p><small>{formatDate(version.validFrom, true)}</small></div></article>)}</div></section>
    <section className="intelligence-block confidence-history"><header><div><Activity size={17} /><h2>Confidence History</h2></div><strong>{decision.confidence}%</strong></header><div className="confidence-trend">{(decision.confidenceHistory || []).map((item, index, values) => <article key={item.id}><i style={{ height: `${Math.max(8, item.confidence)}%` }} className={index > 0 && item.confidence < values[index - 1].confidence ? 'down' : 'up'} /><strong>{item.confidence}%</strong><span>{formatDate(item.recordedAt)}</span><small>{item.reason}</small></article>)}</div>{!isReplay && <form className="confidence-change" onSubmit={updateConfidence}><label>지금 확신 <strong>{confidence}%</strong><input type="range" min={0} max={100} value={confidence} onChange={event => setConfidence(Number(event.target.value))} /></label><input value={confidenceReason} onChange={event => setConfidenceReason(event.target.value)} placeholder="왜 확신이 바뀌었나요?" required /><button className="button secondary">변화 기록</button></form>}</section>
    {isReplay && <section className="intelligence-block replay-compare"><header><div><GitCompareArrows size={17} /><h2>Replay Compare</h2></div><button className="button ghost" onClick={() => void compare()}>THEN ↔ NOW 비교</button></header>{comparison && <><div className="compare-metrics"><article><span>THEN</span><strong>{comparison.from.confidence}%</strong><small>{comparison.from.evidenceCount} evidence · v{comparison.from.version}</small></article><ArrowRight /><article><span>NOW</span><strong>{comparison.to.confidence}%</strong><small>{comparison.to.evidenceCount} evidence · v{comparison.to.version}</small></article></div><div className="compare-changes">{comparison.changes.map(change => <article key={change.kind}><strong>{change.label}</strong><span>{change.before}</span><ArrowRight size={13} /><span>{change.after}</span><small>{change.description}</small></article>)}</div></>}</section>}
    <section className="intelligence-block assumption-tracker"><header><div><ShieldAlert size={17} /><h2>Assumption Tracker</h2></div><span>{decision.assumptionItems?.length || 0}</span></header><div className="assumption-list">{decision.assumptionItems?.map(item => <article key={item.id} className={`assumption-${item.status.toLowerCase()}`}><div><span className="assumption-state">{item.status === 'STRENGTHENED' ? <TrendingUp size={14} /> : ['WEAKENING', 'BROKEN'].includes(item.status) ? <TrendingDown size={14} /> : <Check size={14} />}{item.status}</span><strong>{item.assumption}</strong><small>{item.events?.at(-1)?.reason}</small></div>{!isReplay && <div className="assumption-update"><input value={assumptionReasons[item.id] || ''} onChange={event => setAssumptionReasons(value => ({ ...value, [item.id]: event.target.value }))} placeholder="변화 이유" /><select value={item.status} onChange={event => void updateAssumption(item.id, event.target.value as AssumptionStatus)}>{statuses.map(status => <option key={status}>{status}</option>)}</select></div>}</article>)}</div>{!isReplay && <form className="assumption-add" onSubmit={addAssumption}><input value={assumption} onChange={event => setAssumption(event.target.value)} placeholder="이 판단이 성립하려면 무엇이 참이어야 하나요?" required /><button className="button ghost"><Plus size={15} />전제 추가</button></form>}</section>
    <section className="intelligence-block invalidation-tracker"><header><div><ShieldAlert size={17} /><h2>Invalidation Signals</h2></div><span>{decision.invalidations?.length || 0}</span></header><div className="assumption-list">{decision.invalidations?.map(item => <article key={item.id} className={`assumption-${item.status === 'TRIGGERED' ? 'broken' : item.status === 'RESOLVED' ? 'strengthened' : 'active'}`}><div><span className="assumption-state">{item.status}</span><strong>{item.condition}</strong><small>{item.detectionNote || '아직 충족되지 않음'}</small></div>{!isReplay && <div className="assumption-update"><input value={invalidationNotes[item.id] || ''} onChange={event => setInvalidationNotes(value => ({ ...value, [item.id]: event.target.value }))} placeholder="상태 판단 근거" /><select value={item.status} onChange={event => void updateInvalidation(item.id, event.target.value as 'ACTIVE' | 'TRIGGERED' | 'RESOLVED')}><option>ACTIVE</option><option>TRIGGERED</option><option>RESOLVED</option></select></div>}</article>)}</div>{!isReplay && <form className="assumption-add" onSubmit={addInvalidation}><input value={invalidation} onChange={event => setInvalidation(event.target.value)} placeholder="무엇이 발생하면 이 결정이 틀렸다고 볼 수 있나요?" required /><button className="button ghost"><Plus size={15} />반증 조건 추가</button></form>}</section>
    {decision.latestScore && <section className="intelligence-block quality-score"><header><div><BrainCircuit size={17} /><h2>AI-estimated Decision Quality</h2></div><strong>{decision.latestScore.overall ?? '—'}</strong></header>{decision.latestScore.replayAt && <p className="score-context">REPLAY CONTEXT · {formatDate(decision.latestScore.replayAt, true)}</p>}<div>{Object.entries({ Evidence: decision.latestScore.evidenceQuality, Logic: decision.latestScore.logicQuality, Alternatives: decision.latestScore.alternativeConsideration, Risk: decision.latestScore.riskAwareness, Assumptions: decision.latestScore.assumptionQuality, Calibration: decision.latestScore.calibration, 'Counter evidence': decision.latestScore.counterEvidence }).map(([label, value]) => <article key={label}><span>{label}</span><div><i style={{ width: `${value || 0}%` }} /></div><strong>{value ?? '—'}</strong></article>)}</div><small>AI 분석 시점의 구조적 추정치이며 정답이나 성과 평가가 아닙니다.</small></section>}
    <section className="intelligence-block decision-links"><header><div><Network size={17} /><h2>Decision Network</h2></div><Link to={`/graph`} className="text-link">그래프 열기</Link></header><div className="linked-decisions">{graph?.edges.map(edge => { const target = edge.sourceDecisionId === id ? edge.targetDecisionId : edge.sourceDecisionId; return <article key={edge.id}><Link to={`/decisions/${target}`}><span>{edge.relationType}</span><strong>{linkedTitles.get(target)}</strong><ArrowRight size={14} /></Link>{!isReplay && <button className="icon-button subtle" aria-label="연결 해제" title="연결 해제" onClick={() => void deleteLink(edge.id)}><Trash2 size={14} /></button>}</article> })}</div>{!isReplay && <form className="link-decision" onSubmit={addLink}><select value={linkForm.targetDecisionId} onChange={event => setLinkForm({ ...linkForm, targetDecisionId: event.target.value })} required><option value="">연결할 Decision</option>{allDecisions.map(item => <option value={item.id} key={item.id}>{item.title}</option>)}</select><select value={linkForm.relationType} onChange={event => setLinkForm({ ...linkForm, relationType: event.target.value })}>{relations.map(relation => <option key={relation}>{relation}</option>)}</select><input value={linkForm.description} onChange={event => setLinkForm({ ...linkForm, description: event.target.value })} placeholder="관계 설명" /><button className="button ghost"><Link2 size={15} />연결</button></form>}</section>
    <section className="intelligence-block similar-decisions"><header><div><Search size={17} /><h2>Similar Decisions</h2></div><span>{similar?.fallback ? 'OFFLINE MEMORY' : similar?.model}</span></header>{!similar?.items.length ? <p className="muted-copy">비교할 과거 판단이 아직 없습니다.</p> : similar.items.slice(0, 4).map(item => <Link to={`/decisions/${item.decision.id}`} key={item.decision.id}><div><span>{Math.round(item.contextScore * 100)}% context</span><strong>{item.decision.title}</strong><small>{item.matchedExcerpt}</small></div><ArrowRight /></Link>)}</section>
    <section className="intelligence-block journal"><header><div><History size={17} /><h2>Decision Journal</h2></div><span>{decision.events?.length || 0}</span></header>{decision.events?.slice().reverse().slice(0, 12).map(event => <article key={event.id}><span>{formatDate(event.knownAt, true)}</span><i /><div><strong>{event.eventType.replaceAll('.', ' ')}</strong><small>{JSON.stringify(event.payload)}</small></div></article>)}</section>
  </section>
}
