import * as Switch from '@radix-ui/react-switch'
import { Bot, Building2, Check, ChevronRight, KeyRound, Lock, Network, Save, Shield, SlidersHorizontal, UserPlus, Users } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { NavLink, useLocation, useNavigate } from 'react-router-dom'
import { api, formatDate } from '../lib/api'
import type { AdminSettings, Team, User } from '../types'
import { ErrorNotice, Loading } from '../components/UI'

type Role = { id: string; name: string; description: string; isSystem: boolean; permissions: string[] }
const sections = [
  { id: 'settings', label: '서비스 기본', icon: SlidersHorizontal },
  { id: 'sso', label: 'Keycloak SSO', icon: Network },
  { id: 'ai', label: 'AI 연동', icon: Bot },
  { id: 'workflow', label: '검토와 승인', icon: Check },
  { id: 'teams', label: '팀과 팀장', icon: Building2 },
  { id: 'users', label: '사용자', icon: Users },
  { id: 'roles', label: '역할과 권한', icon: Shield },
]

export default function AdminPage() {
  const location = useLocation(); const navigate = useNavigate(); const section = location.pathname.split('/').filter(Boolean).at(-1) || 'settings'
  const [settings, setSettings] = useState<AdminSettings | null>(null)
  const [users, setUsers] = useState<User[]>([])
  const [roles, setRoles] = useState<Role[]>([])
  const [teams, setTeams] = useState<Team[]>([])
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const loadSettings = () => api<AdminSettings>('/api/v1/admin/settings').then(setSettings).catch(err => setError(err.message))
  const loadUsers = () => api<{ items: User[] }>('/api/v1/admin/users').then(value => setUsers(value.items)).catch(err => setError(err.message))
  const loadRoles = () => api<{ items: Role[] }>('/api/v1/admin/roles').then(value => setRoles(value.items)).catch(err => setError(err.message))
  const loadTeams = () => api<{ items: Team[] }>('/api/v1/admin/teams').then(value => setTeams(value.items)).catch(err => setError(err.message))
  useEffect(() => { if (location.pathname === '/admin' || location.pathname === '/admin/') navigate('/admin/settings', { replace: true }); void loadSettings() }, [])
  useEffect(() => { if (section === 'users') { void loadUsers(); void loadRoles() } if (section === 'roles') void loadRoles(); if (section === 'teams') { void loadUsers(); void loadTeams() } }, [section])
  const save = async (kind: 'branding' | 'oidc' | 'ai' | 'workflow', value: unknown) => { setBusy(true); setError(''); setMessage(''); try { await api(`/api/v1/admin/settings/${kind}`, { method: 'PUT', body: JSON.stringify(value) }); setMessage('설정이 안전하게 저장되었습니다.'); await loadSettings() } catch (err) { setError(err instanceof Error ? err.message : '설정을 저장하지 못했습니다.') } finally { setBusy(false) } }
  if (!settings) return <Loading label="관리 정책을 불러오는 중…" />
  return <div className="admin-layout">
    <aside className="admin-sidebar"><div className="admin-title"><span className="trace-mark">T</span><div><strong>서비스 관리</strong><small>TRACE CONTROL PLANE</small></div></div><nav className="admin-subnav custom-scroll">{sections.map(item => <NavLink to={`/admin/${item.id}`} key={item.id} className={section === item.id ? 'active' : ''}><item.icon size={18} /><span>{item.label}</span><ChevronRight size={15} /></NavLink>)}</nav><div className="admin-security"><Lock size={15} /><span>민감 설정은 AES-256-GCM으로 암호화됩니다.</span></div></aside>
    <main className="admin-content"><header className="admin-header"><div><p className="eyebrow">SERVICE ADMINISTRATION</p><h1>{sections.find(item => item.id === section)?.label}</h1></div><span className="admin-separation"><Building2 size={16} />개인화와 분리된 관리 영역</span></header>{error && <ErrorNotice message={error} />}{message && <div className="success-notice"><Check size={17} />{message}</div>}
      {section === 'settings' && <GeneralSettings value={settings} onChange={setSettings} onSave={() => void save('branding', settings.branding)} busy={busy} />}
      {section === 'sso' && <OIDCSettingsForm value={settings} onChange={setSettings} onSave={() => void save('oidc', settings.oidc)} busy={busy} />}
      {section === 'ai' && <AISettingsForm value={settings} onChange={setSettings} onSave={() => void save('ai', settings.ai)} busy={busy} />}
      {section === 'workflow' && <WorkflowSettingsForm value={settings} onChange={setSettings} onSave={() => void save('workflow', settings.workflow)} busy={busy} />}
      {section === 'teams' && <TeamsPanel teams={teams} users={users} reload={loadTeams} setError={setError} />}
      {section === 'users' && <UsersPanel users={users} roles={roles} reload={loadUsers} setError={setError} />}
      {section === 'roles' && <RolesPanel roles={roles} reload={loadRoles} setError={setError} />}
    </main>
  </div>
}

function Card({ eyebrow, title, description, children, footer }: { eyebrow: string; title: string; description: string; children: React.ReactNode; footer?: React.ReactNode }) { return <section className="admin-card"><header><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{description}</p></header><div className="admin-form">{children}</div>{footer && <footer>{footer}</footer>}</section> }
function SaveButton({ busy, onClick }: { busy: boolean; onClick: () => void }) { return <button className="button primary" disabled={busy} onClick={onClick}><Save size={17} />{busy ? '저장하는 중…' : '변경 저장'}</button> }
function Toggle({ checked, onChange, label, description }: { checked: boolean; onChange: (value: boolean) => void; label: string; description: string }) { return <div className="toggle-row"><div><strong>{label}</strong><span>{description}</span></div><Switch.Root className="switch" checked={checked} onCheckedChange={onChange}><Switch.Thumb /></Switch.Root></div> }

function GeneralSettings({ value, onChange, onSave, busy }: { value: AdminSettings; onChange: (v: AdminSettings) => void; onSave: () => void; busy: boolean }) { return <Card eyebrow="BRANDING" title="서비스 표시" description="로그인과 내비게이션에서 사용하는 서비스 이름과 문구입니다." footer={<SaveButton busy={busy} onClick={onSave} />}><label>서비스명<input value={value.branding.serviceName} onChange={e => onChange({ ...value, branding: { ...value.branding, serviceName: e.target.value } })} /></label><label>슬로건<input value={value.branding.tagline} onChange={e => onChange({ ...value, branding: { ...value.branding, tagline: e.target.value } })} /></label><div className="deployment-contract"><KeyRound /><div><strong>런타임 환경변수 계약</strong><code>POSTGRES_DSN · BOOTSTRAP_ADMIN · BOOTSTRAP_ADMIN_PASSWORD · ENCRYPTION_KEY</code><span>그 외 모든 운영 설정은 이 관리 화면과 PostgreSQL에 저장됩니다.</span></div></div></Card> }

function OIDCSettingsForm({ value, onChange, onSave, busy }: { value: AdminSettings; onChange: (v: AdminSettings) => void; onSave: () => void; busy: boolean }) { const update = (key: string, next: string | boolean) => onChange({ ...value, oidc: { ...value.oidc, [key]: next } }); return <Card eyebrow="OIDC · KEYCLOAK" title="Single Sign-On" description="Issuer, Client ID, Secret만 입력하면 Discovery와 PKCE가 자동 구성됩니다." footer={<SaveButton busy={busy} onClick={onSave} />}><Toggle checked={value.oidc.enabled} onChange={v => update('enabled', v)} label="Keycloak SSO 활성화" description="로그인 화면에 조직 SSO 버튼을 표시합니다." /><div className="form-row"><label>Issuer URL<input value={value.oidc.issuerUrl} onChange={e => update('issuerUrl', e.target.value)} placeholder="https://keycloak.internal/realms/trace" /></label><label>Public Base URL<input value={value.oidc.baseUrl} onChange={e => update('baseUrl', e.target.value)} placeholder="https://trace.internal" /></label></div><div className="form-row"><label>Client ID<input value={value.oidc.clientId} onChange={e => update('clientId', e.target.value)} placeholder="trace" /></label><label>Client Secret<input type="password" value={value.oidc.clientSecret} onChange={e => update('clientSecret', e.target.value)} placeholder="••••••••" /></label></div><label>Redirect URI<code className="read-only-value">{value.oidc.baseUrl ? `${value.oidc.baseUrl}/api/v1/auth/oidc/callback` : 'Public Base URL을 입력하면 자동 생성됩니다.'}</code></label><details className="advanced-settings"><summary>클레임과 Scope 고급 설정</summary><label>Scopes<input value={value.oidc.scopes} onChange={e => update('scopes', e.target.value)} /></label><div className="form-row three"><label>Username claim<input value={value.oidc.usernameClaim} onChange={e => update('usernameClaim', e.target.value)} /></label><label>Email claim<input value={value.oidc.emailClaim} onChange={e => update('emailClaim', e.target.value)} /></label><label>Display claim<input value={value.oidc.displayClaim} onChange={e => update('displayClaim', e.target.value)} /></label></div><Toggle checked={value.oidc.autoProvision} onChange={v => update('autoProvision', v)} label="사용자 자동 프로비저닝" description="첫 SSO 로그인 시 기본 member 역할을 부여합니다." /></details></Card> }

function AISettingsForm({ value, onChange, onSave, busy }: { value: AdminSettings; onChange: (v: AdminSettings) => void; onSave: () => void; busy: boolean }) { const update = (key: string, next: string | number | boolean) => onChange({ ...value, ai: { ...value.ai, [key]: next } }); return <Card eyebrow="PURPLE LAYER" title="AI Provider" description="OpenAI Responses 또는 OpenAI 호환 Chat Completions를 SSE 스트리밍으로 호출합니다." footer={<SaveButton busy={busy} onClick={onSave} />}><Toggle checked={value.ai.enabled} onChange={v => update('enabled', v)} label="AI 분석 활성화" description="Decision Critic, Replay, 반론·패턴 분석을 사용할 수 있습니다." /><div className="form-row"><label>Provider name<input value={value.ai.providerName} onChange={e => update('providerName', e.target.value)} /></label><label>Protocol<select value={value.ai.protocol} onChange={e => update('protocol', e.target.value)}><option value="responses">Responses API</option><option value="chat_completions">Chat Completions compatible</option></select></label></div><label>Base URL<input value={value.ai.baseUrl} onChange={e => update('baseUrl', e.target.value)} placeholder="https://api.openai.com/v1 또는 내부 AI Gateway" /></label><div className="form-row"><label>Analysis model<input value={value.ai.model} onChange={e => update('model', e.target.value)} placeholder="관리자가 선택한 모델 ID" /></label><label>Embedding model<input value={value.ai.embeddingModel || ''} onChange={e => update('embeddingModel', e.target.value)} placeholder="비우면 오프라인 로컬 검색" /><small>설정하면 OpenAI 호환 /embeddings 사용</small></label></div><label>API Key<input type="password" value={value.ai.apiKey} onChange={e => update('apiKey', e.target.value)} placeholder="••••••••" /></label><div className="token-limits"><label>Max output tokens<input type="number" min="1" max="262144" value={value.ai.maxOutputTokens} onChange={e => update('maxOutputTokens', Number(e.target.value))} /><small>최대 262,144 (256K)</small></label><label>Context window<input type="number" min="1" max="262144" value={value.ai.contextWindow} onChange={e => update('contextWindow', Number(e.target.value))} /><small>요청 전 서버에서 크기 검증</small></label><label>Timeout (sec)<input type="number" min="10" max="1800" value={value.ai.requestTimeoutSec} onChange={e => update('requestTimeoutSec', Number(e.target.value))} /><small>10–1,800초</small></label></div><label>System guidance<textarea rows={4} value={value.ai.systemPrompt} onChange={e => update('systemPrompt', e.target.value)} /></label><div className="stream-note"><span className="live-dot" /><div><strong>STREAMING BY DEFAULT</strong><p>브라우저까지 SSE로 전달되며, Replay에서는 미래 데이터가 DB 조회 단계에서 제거됩니다.</p></div></div></Card> }

function WorkflowSettingsForm({ value, onChange, onSave, busy }: { value: AdminSettings; onChange: (v: AdminSettings) => void; onSave: () => void; busy: boolean }) { return <Card eyebrow="OPTIONAL GOVERNANCE" title="검토와 승인 흐름" description="끄면 검토·승인·반려 상태와 사용자 흐름을 제품에서 제외합니다." footer={<SaveButton busy={busy} onClick={onSave} />}><Toggle checked={value.workflow.approvalRequired} onChange={approvalRequired => onChange({ ...value, workflow: { ...value.workflow, approvalRequired } })} label="팀장 승인 프로세스 사용" description="새 판단은 Draft로 만들어지고 요청 후 승인되어야 Active가 됩니다." />{value.workflow.approvalRequired && <div className="workflow-preview"><div className="workflow-node">DRAFT</div><i /><div className="workflow-node amber">REVIEW</div><i /><div className="workflow-node green">APPROVED</div><span>또는</span><div className="workflow-node red">REJECTED</div></div>}<Toggle checked={value.workflow.requireTeamManager} onChange={requireTeamManager => onChange({ ...value, workflow: { ...value.workflow, requireTeamManager } })} label="팀 관리자 지정 필수" description="리뷰어가 없는 팀의 판단은 제출할 수 없습니다." /></Card> }

function UsersPanel({ users, roles, reload, setError }: { users: User[]; roles: Role[]; reload: () => Promise<void>; setError: (v: string) => void }) { const [form, setForm] = useState({ email: '', username: '', displayName: '' }); const submit = async (e: FormEvent) => { e.preventDefault(); try { await api('/api/v1/admin/users', { method: 'POST', body: JSON.stringify(form) }); setForm({ email: '', username: '', displayName: '' }); await reload() } catch (err) { setError(err instanceof Error ? err.message : '사용자를 만들지 못했습니다.') } }; return <><Card eyebrow="DIRECTORY" title="사용자 디렉터리" description="SSO 자동 프로비저닝 전에도 계정을 미리 만들고 상태를 제어할 수 있습니다."><form className="user-create" onSubmit={submit}><input value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="email@example.com" required /><input value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} placeholder="username" required /><input value={form.displayName} onChange={e => setForm({ ...form, displayName: e.target.value })} placeholder="표시 이름" required /><button className="button primary"><UserPlus size={17} />추가</button></form></Card><div className="user-table-wrap custom-scroll"><table className="data-table"><thead><tr><th>사용자</th><th>역할</th><th>등록</th><th>상태</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><span className="avatar">{user.displayName.slice(0, 1)}</span><div><strong>{user.displayName}</strong><small>{user.email}</small></div></td><td>{user.roles.map(role => <span className="chip" key={role}>{role}</span>)}</td><td>{formatDate(user.createdAt)}</td><td><button className={`state-button ${user.status}`} onClick={async () => { await api(`/api/v1/admin/users/${user.id}/status`, { method: 'PATCH', body: JSON.stringify({ status: user.status === 'active' ? 'disabled' : 'active' }) }); await reload() }}>{user.status}</button></td></tr>)}</tbody></table></div><p className="muted small">사용 가능한 역할: {roles.map(role => role.name).join(', ')}</p></> }

function RolesPanel({ roles, reload, setError }: { roles: Role[]; reload: () => Promise<void>; setError: (v: string) => void }) { const allPermissions = Array.from(new Set(roles.flatMap(role => role.permissions))); const [edits, setEdits] = useState<Record<string, string[]>>({}); const selected = (role: Role) => edits[role.id] || role.permissions; const toggle = (role: Role, permission: string) => { if (role.name === 'administrator') return; const current = selected(role); setEdits({ ...edits, [role.id]: current.includes(permission) ? current.filter(item => item !== permission) : [...current, permission] }) }; const saveRole = async (role: Role) => { try { await api(`/api/v1/admin/roles/${role.id}/permissions`, { method: 'PUT', body: JSON.stringify({ permissions: selected(role) }) }); await reload() } catch (err) { setError(err instanceof Error ? err.message : '권한을 저장하지 못했습니다.') } }; return <div className="role-list">{roles.map(role => <Card key={role.id} eyebrow={role.isSystem ? 'SYSTEM ROLE' : 'CUSTOM ROLE'} title={role.name} description={role.description} footer={<button className="button secondary" disabled={role.name === 'administrator'} onClick={() => void saveRole(role)}><Save size={16} />권한 저장</button>}><div className="permission-grid">{allPermissions.map(permission => <label key={permission} className={selected(role).includes(permission) ? 'permission selected' : 'permission'}><input type="checkbox" checked={selected(role).includes(permission)} disabled={role.name === 'administrator'} onChange={() => toggle(role, permission)} /><span>{permission}</span></label>)}</div></Card>)}</div> }

function TeamsPanel({ teams, users, reload, setError }: { teams: Team[]; users: User[]; reload: () => Promise<void>; setError: (v: string) => void }) { const [form,setForm]=useState({name:'',description:'',managerUserId:'',memberIds:[] as string[]});const submit=async(e:FormEvent)=>{e.preventDefault();try{await api('/api/v1/admin/teams',{method:'POST',body:JSON.stringify(form)});setForm({name:'',description:'',managerUserId:'',memberIds:[]});await reload()}catch(err){setError(err instanceof Error?err.message:'팀을 만들지 못했습니다.')}};return <><Card eyebrow="TEAM DIRECTORY" title="팀과 검토 책임자" description="승인 흐름에서 각 판단을 검토할 팀장을 지정합니다."><form className="team-create" onSubmit={submit}><div className="form-row"><label>팀 이름<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required /></label><label>팀장<select value={form.managerUserId} onChange={e=>setForm({...form,managerUserId:e.target.value})} required><option value="">선택</option>{users.filter(u=>u.status==='active').map(u=><option value={u.id} key={u.id}>{u.displayName}</option>)}</select></label></div><label>설명<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} /></label><fieldset className="member-picker"><legend>팀원</legend>{users.filter(u=>u.status==='active').map(u=><label key={u.id}><input type="checkbox" checked={form.memberIds.includes(u.id)} onChange={()=>setForm({...form,memberIds:form.memberIds.includes(u.id)?form.memberIds.filter(id=>id!==u.id):[...form.memberIds,u.id]})}/><span>{u.displayName}</span></label>)}</fieldset><button className="button primary"><UserPlus size={17}/>팀 생성</button></form></Card><div className="team-list">{teams.map(team=><article key={team.id}><div className="team-symbol"><Building2/></div><div><strong>{team.name}</strong><span>{team.description}</span><small>팀장 {team.managerName||'—'} · {team.memberCount}명</small></div></article>)}</div></>}
