import { BrainCircuit, Compass, Gauge, Pause, Play, Scale, Sparkles, Target } from 'lucide-react'
import { useEffect, useState } from 'react'
import { api } from '../lib/api'
import type { Analytics, Decision } from '../types'
import { Empty, ErrorNotice, Loading, PageHeader } from '../components/UI'

const biasName: Record<string, string> = { CONFIRMATION_BIAS: 'Confirmation Bias', OVERCONFIDENCE: 'Overconfidence', NARROW_ALTERNATIVES: 'Alternative Blind Spot', RISK_BLIND_SPOT: 'Risk Blind Spot' }

export default function InsightsPage() {
  const [items, setItems] = useState<Decision[] | null>(null)
  const [metrics, setMetrics] = useState<Analytics | null>(null)
  const [aiText, setAIText] = useState('')
  const [aiBusy, setAIBusy] = useState(false)
  const [error, setError] = useState('')
  useEffect(() => { Promise.all([api<{ items: Decision[] }>('/api/v1/decisions?limit=100'), api<Analytics>('/api/v1/analytics/calibration')]).then(([list, analytics]) => { setItems(list.items); setMetrics(analytics) }).catch(err => setError(err.message)) }, [])
  const runPatternAI = async () => { if (aiBusy) return; setAIText(''); setAIBusy(true); setError(''); try { const response = await fetch('/api/v1/ai/patterns/stream', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Trace-Request': '1' }, body: JSON.stringify({ prompt: '나의 반복 판단 패턴과 다음 결정 전에 확인할 질문을 분석해 주세요.' }) }); if (!response.ok || !response.body) { const value = await response.json().catch(() => null); throw new Error(value?.error?.message || 'AI 패턴 분석을 시작하지 못했습니다.') } const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ''; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const chunks = buffer.split('\n\n'); buffer = chunks.pop() || ''; for (const chunk of chunks) { const event = chunk.match(/^event: (.+)$/m)?.[1]; const data = chunk.match(/^data: (.+)$/m)?.[1]; if (event === 'delta' && data) setAIText(text => text + (JSON.parse(data) as { text: string }).text) } } } catch (err) { setError(err instanceof Error ? err.message : 'AI 패턴 분석 중 오류가 발생했습니다.') } finally { setAIBusy(false) } }
  if (!items || !metrics) return <Loading label="개인 판단 패턴을 계산하는 중…" />
  return <div className="page insights-page"><PageHeader eyebrow="PERSONAL DECISION INTELLIGENCE" title="판단 패턴"><span>여러 Decision의 확신·근거·전제·결과를 연결해 나의 판단 습관을 읽습니다.</span></PageHeader>{error && <ErrorNotice message={error} />}
    {!items.length ? <Empty title="패턴을 만들 판단이 아직 없습니다."><p>몇 개의 판단과 회고가 쌓이면 확신 보정과 반복 편향을 볼 수 있습니다.</p></Empty> : <>
      <section className="pattern-hero"><div><Sparkles size={20} /><p className="eyebrow">YOUR DECISION STYLE</p><h2>{metrics.profile.summary || '당신의 판단 데이터가 시간과 함께 선명해집니다.'}</h2><p>현재 {metrics.totalDecisions}개의 판단을 서로 비교했습니다. 이것은 성격 진단이 아니라 기록에서 관찰된 현재 패턴입니다.</p></div><div className="calibration-orbit"><span>{Math.round(metrics.averageConfidence)}%</span><small>평균 확신</small><i className="orbit one" /><i className="orbit two" /></div></section>
      <section className="insight-metrics"><article><Target /><span>AVERAGE CONFIDENCE</span><strong>{Math.round(metrics.averageConfidence)}</strong><p>기록 당시의 평균 확신</p></article><article><Compass /><span>EVIDENCE DEPTH</span><strong>{metrics.evidenceDepth.toFixed(1)}</strong><p>판단당 평균 근거 수</p></article><article><BrainCircuit /><span>REFLECTION RATE</span><strong>{Math.round(metrics.reflectionRate)}%</strong><p>회고를 남긴 판단 비율</p></article></section>
      <section className="profile-section"><header><div><p className="eyebrow">DECISION PROFILE</p><h2>현재 판단 스타일</h2></div><Gauge /></header><div className="profile-dimensions">{Object.entries({ 'Evidence-driven': metrics.profile.evidenceDriven, 'Risk tolerance': metrics.profile.riskTolerance, 'Alternative thinking': metrics.profile.alternativeThinking, 'Decision speed': metrics.profile.decisionSpeed, 'Confidence': metrics.profile.confidenceStyle, 'Reflection': metrics.profile.reflectionHabit }).map(([label, value]) => <div key={label}><span>{label}</span><strong className={`level-${value.toLowerCase()}`}>{value}</strong></div>)}</div></section>
      <section className="calibration-section"><header><div><p className="eyebrow">CONFIDENCE CALIBRATION</p><h2>확신과 실제 적중률</h2></div><Gauge /></header>{metrics.calibration.length === 0 ? <p className="muted-copy">Outcome이 기록되면 확신 구간별 실제 결과를 비교합니다.</p> : <div className="calibration-chart">{metrics.calibration.map(bucket => <div key={bucket.confidence}><div className="calibration-bars"><i className="expected" style={{ height: `${bucket.confidence}%` }} title={`당시 확신 ${bucket.confidence}%`} /><i className="actual" style={{ height: `${bucket.successRate}%` }} title={`실제 성공률 ${Math.round(bucket.successRate)}%`} /></div><strong>{bucket.confidence}–{bucket.confidence === 100 ? 100 : bucket.confidence + 9}</strong><small>{bucket.count}건 · {Math.round(bucket.successRate)}%</small></div>)}</div>}<div className="chart-legend"><span><i className="expected" />당시 확신</span><span><i className="actual" />실제 성공률</span></div></section>
      <div className="intelligence-grid"><section className="pattern-list"><header><div><p className="eyebrow">REPEATED PATTERNS</p><h2>반복 패턴</h2></div><BrainCircuit /></header>{(metrics.patterns || []).map(pattern => <article key={pattern.code}><span className={`pattern-strength ${pattern.strength.toLowerCase()}`}>{pattern.strength}</span><div><strong>{pattern.title}</strong><p>{pattern.description}</p></div></article>)}</section><section className="bias-profile"><header><div><p className="eyebrow">BIAS PROFILE</p><h2>주의할 신호</h2></div><Compass /></header>{!metrics.biases?.length ? <p className="muted-copy">현재 기록에서 반복 편향 신호가 발견되지 않았습니다.</p> : metrics.biases.map(bias => <article key={bias.biasType}><div><strong>{biasName[bias.biasType] || bias.biasType}</strong><span>{bias.count} decisions</span></div><div className="bias-bar"><i style={{ width: `${Math.min(100, bias.percentage)}%` }} /></div><b>{Math.round(bias.percentage)}%</b></article>)}</section></div>
      <section className="decision-matrix"><header><div><p className="eyebrow">DECISION MATRIX</p><h2>Skill, Luck, Mistake</h2></div><Scale /></header><div className="matrix-grid"><span className="matrix-y good">판단 좋음</span><span className="matrix-y bad">판단 나쁨</span><span className="matrix-x good">결과 좋음</span><span className="matrix-x bad">결과 나쁨</span><article className="skill"><strong>{metrics.skill}</strong><span>SKILL</span></article><article className="bad-luck"><strong>{metrics.badLuck}</strong><span>BAD LUCK</span></article><article className="good-luck"><strong>{metrics.goodLuck}</strong><span>GOOD LUCK</span></article><article className="mistake"><strong>{metrics.mistake}</strong><span>MISTAKE</span></article></div></section>
      <section className="ai-layer pattern-ai"><div className="ai-head"><div><Sparkles size={18} /><span>AI PATTERN INTELLIGENCE</span></div><BrainCircuit size={20} /></div>{aiText ? <div className="ai-output">{aiText}</div> : <p>여러 판단의 관계를 AI가 함께 읽도록 요청할 수 있습니다. 관찰과 가설을 분리해 설명합니다.</p>}<button className="button purple" disabled={aiBusy} onClick={() => void runPatternAI()}>{aiBusy ? <Pause size={16} /> : <Play size={16} />}{aiBusy ? '분석 중…' : '내 반복 패턴 분석'}</button></section>
    </>}
  </div>
}
