import { Check, Copy, KeyRound, Plus, RefreshCw, ShieldCheck, Trash2 } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { api, formatDate } from '../lib/api'
import type { APIToken, PersonalKey } from '../types'
import { ErrorNotice, Loading, PageHeader } from '../components/UI'

export default function PersonalPage() {
  const [keys, setKeys] = useState<PersonalKey[] | null>(null)
  const [tokens, setTokens] = useState<APIToken[] | null>(null)
  const [keyForm, setKeyForm] = useState({ name: '', kind: 'ai_provider', value: '', permissions: 'use' })
  const [tokenName, setTokenName] = useState('')
  const [plainToken, setPlainToken] = useState('')
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const load = () => Promise.all([api<{ items: PersonalKey[] }>('/api/v1/personal/keys'), api<{ items: APIToken[] }>('/api/v1/personal/tokens')]).then(([a, b]) => { setKeys(a.items); setTokens(b.items) }).catch(err => setError(err.message))
  useEffect(() => { void load() }, [])
  if (!keys || !tokens) return <Loading />
  const createKey = async (event: FormEvent) => { event.preventDefault(); try { await api('/api/v1/personal/keys', { method: 'POST', body: JSON.stringify({ ...keyForm, permissions: keyForm.permissions.split(',').map(v => v.trim()).filter(Boolean), expiresAt: null }) }); setKeyForm({ name: '', kind: 'ai_provider', value: '', permissions: 'use' }); setMessage('개인 키가 암호화되어 저장되었습니다.'); await load() } catch (err) { setError(err instanceof Error ? err.message : '키를 만들지 못했습니다.') } }
  const rotateKey = async (key: PersonalKey) => { const value = window.prompt(`${key.name}의 새 키 값을 입력하세요.`); if (!value) return; await api(`/api/v1/personal/keys/${key.id}/rotate`, { method: 'POST', body: JSON.stringify({ value }) }); setMessage(`${key.name} 키가 회전되었습니다.`); await load() }
  const createToken = async () => { if (!tokenName.trim()) return; try { const result = await api<{ token: APIToken; plainTextToken: string }>('/api/v1/personal/tokens', { method: 'POST', body: JSON.stringify({ name: tokenName, scopes: ['decisions:read', 'decisions:write'], expiresAt: null }) }); setPlainToken(result.plainTextToken); setTokenName(''); await load() } catch (err) { setError(err instanceof Error ? err.message : '토큰을 만들지 못했습니다.') } }
  const rotateDataKey = async () => { if (!confirm('모든 개인 비밀을 새 데이터 키로 다시 암호화할까요?')) return; await api('/api/v1/personal/data-key/rotate', { method: 'POST' }); setMessage('개인 데이터 암호화 키 회전이 완료되었습니다.') }
  return <div className="page personal-page"><PageHeader eyebrow="PERSONAL SPACE" title="개인화와 키"><span>서비스 관리 설정과 분리된, 나만의 보안·연동 공간입니다.</span></PageHeader>{error && <ErrorNotice message={error} />}{message && <div className="success-notice"><Check size={17} />{message}</div>}
    <section className="security-banner"><div><ShieldCheck /><div><p className="eyebrow">ENVELOPE ENCRYPTION</p><h2>개인 키는 사용자별 데이터 키로 보호됩니다.</h2><p>루트 키는 런타임 밖으로 나오지 않으며, 키 회전 시 모든 개인 비밀을 트랜잭션 안에서 다시 암호화합니다.</p></div></div><button className="button secondary" onClick={() => void rotateDataKey()}><RefreshCw size={17} />데이터 키 회전</button></section>
    <div className="personal-grid"><section className="settings-card"><header><div><p className="eyebrow">PERSONAL KEYS</p><h2>내 키</h2></div><KeyRound /></header><form className="compact-form" onSubmit={createKey}><div className="form-row"><label>이름<input value={keyForm.name} onChange={e => setKeyForm({ ...keyForm, name: e.target.value })} placeholder="My AI key" required /></label><label>유형<select value={keyForm.kind} onChange={e => setKeyForm({ ...keyForm, kind: e.target.value })}><option value="ai_provider">AI Provider</option><option value="integration">Integration</option><option value="signing">Signing</option><option value="other">Other</option></select></label></div><label>비밀 값<input type="password" value={keyForm.value} onChange={e => setKeyForm({ ...keyForm, value: e.target.value })} required /></label><label>권한 (쉼표 구분)<input value={keyForm.permissions} onChange={e => setKeyForm({ ...keyForm, permissions: e.target.value })} /></label><button className="button primary"><Plus size={17} />키 추가</button></form><div className="key-list">{keys.map(key => <article key={key.id}><span className={`key-status ${key.status}`} /><div><strong>{key.name}</strong><small>{key.kind} · {key.permissions.join(', ')}</small><small>회전 {formatDate(key.lastRotatedAt)}</small></div><div><button className="icon-button" title="키 권한 변경" onClick={async()=>{const next=window.prompt('권한을 쉼표로 구분해 입력하세요.',key.permissions.join(', '));if(!next)return;await api(`/api/v1/personal/keys/${key.id}/permissions`,{method:'PATCH',body:JSON.stringify({permissions:next.split(',').map(value=>value.trim()).filter(Boolean)})});await load()}}><ShieldCheck /></button><button className="icon-button" title="키 회전" onClick={() => void rotateKey(key)}><RefreshCw /></button><button className="icon-button danger" title="키 폐기" onClick={async () => { await api(`/api/v1/personal/keys/${key.id}`, { method: 'DELETE' }); await load() }}><Trash2 /></button></div></article>)}</div></section>
      <section className="settings-card"><header><div><p className="eyebrow">API & MCP ACCESS</p><h2>개인 액세스 토큰</h2></div><span className="protocol-badge">MCP 2025-11-25</span></header><p className="muted">REST API와 <code>/mcp</code>에서 Bearer 토큰으로 사용합니다. 원문은 생성 시 한 번만 보입니다.</p>{plainToken && <div className="one-time-secret"><span>지금 복사하세요</span><code>{plainToken}</code><button className="icon-button" onClick={() => navigator.clipboard.writeText(plainToken)}><Copy /></button></div>}<div className="token-create"><input value={tokenName} onChange={e => setTokenName(e.target.value)} placeholder="Token name" /><button className="button primary" onClick={() => void createToken()}><Plus size={17} />발급</button></div><div className="token-list">{tokens.map(token => <article key={token.id}><div><strong>{token.name}</strong><code>{token.prefix}…</code><small>{token.scopes.join(' · ')}</small></div><button className="icon-button danger" onClick={async () => { await api(`/api/v1/personal/tokens/${token.id}`, { method: 'DELETE' }); await load() }}><Trash2 /></button></article>)}</div></section>
    </div>
  </div>
}
