export type VersionInfo = { service: string; version: string; commit: string; buildTime: string }
export type User = { id: string; email: string; username: string; displayName: string; status: string; locale: string; timezone: string; roles: string[]; permissions: string[]; createdAt: string }
export type PublicConfig = { branding: { serviceName: string; tagline: string }; oidc: { enabled: boolean; loginUrl: string }; workflow: WorkflowSettings; version: VersionInfo }
export type Alternative = { id: string; title: string; description: string }
export type Evidence = { id: string; title: string; type: string; source: string; content: string; snapshot?: string; summary: string; reliability?: number; stance: 'support' | 'neutral' | 'against'; publishedAt?: string; knownAt: string; capturedAt: string }
export type Expectation = { id: string; expectation: string; successCriteria: string; expectedAt?: string; probability?: number }
export type Outcome = { id: string; result: string; outcomeScore: number; decisionQuality?: number; outcomeAt: string; createdAt: string }
export type Reflection = { id: string; reflection: string; learning: string; reasoningStillSound?: boolean; createdAt: string }
export type AIInsight = { id: string; insightType: string; content: { text?: string }; model: string; promptVersion: string; replayAt?: string; inputSnapshotHash: string; generatedAt: string }
export type DecisionEvent = { id: string; eventType: string; payload: Record<string, unknown>; effectiveAt: string; knownAt: string; createdAt: string }
export type ConfidenceRecord = { id: string; decisionId: string; confidence: number; reason: string; recordedAt: string; createdAt: string }
export type AssumptionEvent = { id: string; previousStatus?: string; status: AssumptionStatus; reason: string; evidenceId?: string; knownAt: string; createdAt: string }
export type AssumptionStatus = 'UNKNOWN' | 'ACTIVE' | 'STRENGTHENED' | 'WEAKENING' | 'BROKEN'
export type Assumption = { id: string; decisionId: string; assumption: string; status: AssumptionStatus; knownAt: string; createdAt: string; updatedAt: string; events?: AssumptionEvent[] }
export type InvalidationCondition = { id: string; decisionId: string; condition: string; status: 'ACTIVE' | 'TRIGGERED' | 'RESOLVED'; evidenceId?: string; detectionNote: string; knownAt: string; triggeredAt?: string; createdAt: string; updatedAt: string }
export type DecisionScore = { evidenceQuality?: number; logicQuality?: number; alternativeConsideration?: number; riskAwareness?: number; assumptionQuality?: number; calibration?: number; counterEvidence?: number; overall?: number; replayAt?: string; estimatedAt: string }
export type Decision = { id: string; ownerId: string; ownerName?: string; teamId?: string; title: string; category: string; decision: string; reason: string; assumptions: string; invalidationConditions: string; confidence: number; status: string; workflowState: string; decidedAt: string; reviewAt?: string; createdAt: string; updatedAt: string; version: number; alternatives?: Alternative[]; evidence?: Evidence[]; expectations?: Expectation[]; outcomes?: Outcome[]; reflections?: Reflection[]; insights?: AIInsight[]; events?: DecisionEvent[]; assumptionItems?: Assumption[]; invalidations?: InvalidationCondition[]; confidenceHistory?: ConfidenceRecord[]; latestScore?: DecisionScore; health?: string }
export type ReviewItem = { decisionId: string; title: string; category: string; confidence: number; priority: number; health: string; reasons: string[]; reviewAt?: string; lastReviewed?: string; updatedAt: string }
export type Dashboard = { activeCount: number; waitingCount: number; reviewDue: number; closedCount: number; recent: Decision[]; reviewInbox?: ReviewItem[] }
export type WorkflowSettings = { approvalRequired: boolean; requireTeamManager: boolean }
export type OIDCSettings = { enabled: boolean; issuerUrl: string; clientId: string; clientSecret: string; scopes: string; usernameClaim: string; emailClaim: string; displayClaim: string; autoProvision: boolean; baseUrl: string }
export type AISettings = { enabled: boolean; providerName: string; baseUrl: string; protocol: 'responses' | 'chat_completions'; apiKey: string; model: string; embeddingModel: string; maxOutputTokens: number; contextWindow: number; requestTimeoutSec: number; systemPrompt: string }
export type AdminSettings = { oidc: OIDCSettings; ai: AISettings; workflow: WorkflowSettings; branding: { serviceName: string; tagline: string }; limits: { maxTokens: number } }
export type PersonalKey = { id: string; name: string; kind: string; permissions: string[]; status: string; expiresAt?: string; lastRotatedAt: string; createdAt: string }
export type APIToken = { id: string; name: string; prefix: string; scopes: string[]; lastUsedAt?: string; expiresAt?: string; createdAt: string }
export type Approval = { id: string; decisionId: string; decisionTitle: string; requesterId: string; requesterName: string; reviewerId?: string; state: string; requestNote: string; responseNote: string; requestedAt: string; resolvedAt?: string }
export type Team = { id: string; name: string; description: string; managerUserId?: string; managerName?: string; memberIds: string[]; memberCount: number; createdAt: string }
export type BiasProfileItem = { biasType: string; count: number; percentage: number; byCategory: Record<string, number> }
export type PatternInsight = { code: string; title: string; description: string; strength: string }
export type DecisionProfile = { evidenceDriven: string; riskTolerance: string; alternativeThinking: string; decisionSpeed: string; confidenceStyle: string; reflectionHabit: string; summary: string }
export type Analytics = { totalDecisions: number; averageConfidence: number; evidenceDepth: number; reflectionRate: number; skill: number; badLuck: number; goodLuck: number; mistake: number; calibration: { confidence: number; count: number; successRate: number }[]; biases: BiasProfileItem[]; patterns: PatternInsight[]; profile: DecisionProfile }
export type DecisionVersion = { id: string; decisionId: string; version: number; title: string; category: string; decision: string; reason: string; assumptions: string; invalidationConditions: string; confidence: number; status: string; workflowState: string; decidedAt: string; reviewAt?: string; changeReason: string; validFrom: string; validTo?: string; createdAt: string }
export type DecisionLink = { id: string; sourceDecisionId: string; targetDecisionId: string; relationType: string; description: string; effectiveAt: string; createdAt: string }
export type GraphNode = { id: string; title: string; category: string; status: string; confidence: number; outcome?: number; decidedAt: string; depth: number; health: string }
export type DecisionGraph = { focusId?: string; at?: string; nodes: GraphNode[]; edges: DecisionLink[] }
export type ReplaySnapshot = { at: string; version: number; confidence: number; evidenceCount: number; alternativeCount: number; assumptionCount: number; atRiskAssumptions: number; outcomeCount: number; latestOutcomeScore?: number; decision: Decision }
export type ReplayComparison = { from: ReplaySnapshot; to: ReplaySnapshot; changes: { kind: string; label: string; before: string; after: string; description: string }[] }
export type SimilarDecision = { decision: Decision; similarity: number; contextScore: number; matchedExcerpt: string; reasons: string[] }
export type SemanticSearchResult = { query: string; model: string; fallback: boolean; items: SimilarDecision[] }
